### ISSUE TITLE
Import Command

### ISSUE THREAD

**Issue by hanydd** [CS2103AUG2017-F11-B4/main#20]
Add Import Command, which will read a exported XML file of persons and add them into your address book.

- Usage: import [FILE PATH]

- [x] be able to update address Book given a valid XML file
- [x] be able to detect duplicated persons in the file
- [x] be able to detect file errors (not in xml format, missing file, etc.)
- [x] unit tests and system tests should be implemented

**Comment by zenghou** [comment]
@HanYaodong please remember to close this issue after your PR is merged
