### ISSUE TITLE
Duplicates not detected for person with same name, phone and e-mail but different address and birthday

### ISSUE THREAD

**Issue by chuaweiwen** [CS2103AUG2017-F11-B4/main#49]
Duplicate contacts can be added with a person with the same name, same phone, same e-mail but different address and different birthday.

The following can be added to the contacts:
- Name: Joshua, Phone: 61515151, Email: joshua@gmail.com, Address: <blank>, Birthday: <blank>, Tag: <blank>
- (same name, phone, email), Address: (address 1), Birthday: <blank>, Tag: <blank>
- (same name, phone, email), Address: (address 1), Birthday: <date 1>, Tag: <blank>
- (same name, phone, email), Address: (address 1), Birthday: <date 2>, Tag: <blank>
- (same name, phone, email), Address: (address 2), Birthday: <blank>, Tag: <blank>

![image](https://user-images.githubusercontent.com/19780314/32363154-cb89da78-c0a8-11e7-9942-2aab3ca3bc3a.png)

**Comment by sunarjo-denny** [comment]
The above are not considered duplicates
- People of different birthdays are considered different people
- People of different address are considered different as current Address Book does not allow multiple address storage
